export const ActionType =
    {
        LANG_CHANGE: 'LANG_CHANGE',

        USER_CREATE: 'USER_CREATE',
        USER_VERIFY_EMAIL: 'USER_VERIFY_EMAIL',
        USER_SIGN_UP: 'USER_SIGN_UP',
        USER_SIGN_IN: 'USER_SIGN_IN',

        ALERT_ERR_API: 'ALERT_ERR_API',
        ALERT_INFO: 'ALERT_INFO',

        DLG_LOGIN: 'DLG_LOGIN',
        DLG_REGISTER_DIALOG_1: 'DLG_REGISTER_DIALOG_1',
        DLG_REGISTER_DIALOG_2: 'DLG_REGISTER_DIALOG_2',
        DLG_REGISTER_DIALOG_2_OK: 'DLG_REGISTER_DIALOG_2_OK',
        DLG_REGISTER_DIALOG_3: 'DLG_REGISTER_DIALOG_3',

        SESSION_REFRESH: 'SESSION_REFRESH',
    }

